### ISSUE TITLE
Open source from Macau government ?

### ISSUE THREAD

**Issue by kitkimwong** [ngsiolei/macau-bus-data#1]
Hello, I wounder ask those json data is open source from Macau GM?
If yes, would you mind tell me how to get it? Have any Interface or callback from macau gm?
thanks

**Comment by ngsiolei** [comment]
Actually DSAT didn't open bus route data for public.

At DSAT website, there is a page [Point-to-point route search](http://www.dsat.gov.mo/bus/tc/bus_ptp.aspx), it allows us to show the selected result on the map, which exposes the data links, e.g.,

the following link template returns path geometry of specified `ROUTE_ID`, replace `{id}` by a valid `ROUTE_ID`

```
http://www.dsat.gov.mo/bres/EBIP_REVAMP/proxy/proxy.ashx?http://doisrvgis_ha/ArcGIS/rest/services/BRESR_PRODUCTION/EBIP_BUS_ROUTE/MapServer/0/query?f=json&where=(ROUTE_ID%20%3D%20{id})&returnGeometry=true&outFields=*
```

the following link template returns stops of specified `ROUTE_ID`, replace `{id}` by a valid `ROUTE_ID`

```
http://www.dsat.gov.mo/bres/EBIP_REVAMP/proxy/proxy.ashx?http://doisrvgis_ha/ArcGIS/rest/services/BRESR_PRODUCTION/EBIP_BUS_STOP/MapServer/0/query?f=json&where=(ROUTE_ID%20%3D%20{id})&returnGeometry=true&spatialRel=esriSpatialRelIntersects&outFields=*&outSR=102159
```

Note
- `ROUTE_ID` represents the ID of a sub path in a route. Let's say route 1, a 2-way route, with 2 sub paths and 2 `ROUTE_ID`s (6 and 8). Study the data for more details.
- To convert Macau grid coordinate (used inside the returned data) to Latitude/Longitude, i use https://github.com/ngsiolei/MacauGrid

**Comment by kitkimwong** [comment]
That's great! Awesome! Thank you a lot. :)
